name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Export static pages
      run: |
        npm install
        npm run build
        npm run export
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_TOKEN }}
        external_repository: cuso4-5h2o/springboard
        publish_branch: pages
        publish_dir: ./out
    - name: Purge Cloudflare cache
      env:
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        CF_PURGE_CACHE_TOKEN: ${{ secrets.CF_PURGE_CACHE_TOKEN }}
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" \
         -H "Authorization: Bearer $CF_PURGE_CACHE_TOKEN" \
         -H "Content-Type: application/json" \
         --data "{\"purge_everything\": true}"
