
# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Export static pages
      run: |
        npm install
        npm run build
        npm run export
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GP_DEPLOY_TOKEN }}
        external_repository: cuso4-5h2o/springboard
        publish_branch: pages
        publish_dir: ./out
    - name: Purge Cloudflare cache
      env:
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        CF_PURGE_CACHE_TOKEN: ${{ secrets.CF_PURGE_CACHE_TOKEN }}
      run: |
        curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" \
         -H "Authorization: Bearer $CF_PURGE_CACHE_TOKEN" \
         -H "Content-Type: application/json" \
         --data '{"purge_everything":true}'
